### ISSUE TITLE
[Feature request] Device information / backend / user viewable

### ISSUE THREAD

**Issue by iamluca** [discord-images/discord-images#2]
**Device Information**
( viewable by admin and end user )
 - [x] IP
 - [x] Browser
 - [x] Operating System

**Comment by iamluca** [comment]
@Michael55555 Please work on this for the new update so we can release it as soon as possible.

**Comment by iamluca** [comment]
The IP address is already listed in the `files` DB when you post a file if you could just grab the last file uploaded by the user then push it to the tab. Bam! Done. Just make it now. @Michael55555

**Comment by Michael55555** [comment]
So finally the user will just have a short dashboard with his IP, browser, operating system?

**Comment by iamluca** [comment]
@Michael55555 When clicking currently, your not able to press it or get the information you need. Please help me and work on this with me.
