### ISSUE TITLE
Change from wumpus logo to a different logo - DMCA request

### ISSUE THREAD

**Issue by iamluca** [discord-images/discord-images#23]

**Comment by iilukas** [comment]
This was in compliance with the Discord DMCA request. Please review https://github.com/discord-images/transparency/blob/master/dmca/2018-09-19.asc

**Comment by iilukas** [comment]
@Michael55555 Help to find a GFX Designer, they will be getting paid.

**Comment by iamluca** [comment]
This has been posted and we're waiting for the graphics designer to make us a logo. kthxbye :wave:
