### ISSUE TITLE
Add footer 

### ISSUE THREAD

**Issue by iilukas** [discord-images/discord-images#24]
Not endorsed or affiliated with Discord Inc

**Comment by Michael55555** [comment]
Which what should be the text of the footer?

**Comment by iilukas** [comment]
@Michael55555 The text or footer shall be displayed on any publicly viewable area of the website except for the images obviously. This is in compliance with the recent DMCA by Discord. 

For further information, please visit: https://github.com/discord-images/transparency/blob/master/dmca/2018-09-19.asc

**Comment by iilukas** [comment]
This needs to have a pull request before Friday / Saturday.

**Comment by iilukas** [comment]
This issue has been completed. This feature request was issued by Discord Trust & Safety team. kthxbye :wave:
